// This file is part of Edgehog.
//
// Copyright 2026 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
/// Upload a new or replace a configuration file
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutRequest {
    /// Name of the configuration file
    #[prost(string, tag = "1")]
    pub file_name: ::prost::alloc::string::String,
    /// Flag to persist the configuration
    #[prost(bool, tag = "2")]
    pub persist: bool,
    /// Configuration file for the runtime.
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<Config>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutResponse {}
/// Configuration file for the device runtime.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    /// Connection to use.
    #[prost(enumeration = "config::Connection", optional, tag = "1")]
    pub connection: ::core::option::Option<i32>,
    /// Configuration for the Astarte Device SDK
    #[prost(message, optional, tag = "2")]
    pub astarte_device_sdk: ::core::option::Option<AstarteDeviceConfig>,
    /// Configuration for the Astarte Message Hub SDK
    #[prost(message, optional, tag = "3")]
    pub astarte_message_hub: ::core::option::Option<MessageHubConfig>,
    /// Configuration for the Container service.
    #[prost(message, optional, tag = "4")]
    pub containers: ::core::option::Option<ContainerConfig>,
    /// Configuration for the OTA service.
    #[prost(message, optional, tag = "5")]
    pub ota: ::core::option::Option<OtaConfig>,
    /// Configuration for the FileTransfer service.
    #[prost(message, optional, tag = "6")]
    pub file_transfer: ::core::option::Option<FileTransferConfig>,
    /// Configuration for the Forwarder service.
    #[prost(message, optional, tag = "7")]
    pub forwarder: ::core::option::Option<ForwarderConfig>,
    /// Persistent writable directory to use for storage.
    #[prost(string, optional, tag = "8")]
    pub store_directory: ::core::option::Option<::prost::alloc::string::String>,
    /// Configuration for a telemetry interface
    #[prost(map = "string, message", tag = "9")]
    pub telemetry_config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        TelemetryConfig,
    >,
}
/// Nested message and enum types in `Config`.
pub mod config {
    /// Connection type to use
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Connection {
        /// Default connection
        Unspecified = 0,
        /// Connect to Astarte directly
        LibraryDirect = 1,
        /// Connect to Astarte through the MessageHub
        LibraryMessageHub = 2,
    }
    impl Connection {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "CONNECTION_UNSPECIFIED",
                Self::LibraryDirect => "CONNECTION_LIBRARY_DIRECT",
                Self::LibraryMessageHub => "CONNECTION_LIBRARY_MESSAGE_HUB",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CONNECTION_UNSPECIFIED" => Some(Self::Unspecified),
                "CONNECTION_LIBRARY_DIRECT" => Some(Self::LibraryDirect),
                "CONNECTION_LIBRARY_MESSAGE_HUB" => Some(Self::LibraryMessageHub),
                _ => None,
            }
        }
    }
}
/// / Configuration for the Astarte Device SDK
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AstarteDeviceConfig {
    /// / Astarte pairing URL
    #[prost(string, tag = "1")]
    pub pairing_url: ::prost::alloc::string::String,
    /// / Realm of the device
    #[prost(string, tag = "2")]
    pub realm: ::prost::alloc::string::String,
    /// / Device ID
    #[prost(string, optional, tag = "3")]
    pub device_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub credentials_secret: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub pairing_token: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub ignore_ssl: ::core::option::Option<::prost::alloc::string::String>,
}
/// / Configuration for the Astarte MessageHub
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageHubConfig {
    #[prost(string, tag = "1")]
    pub endpoint: ::prost::alloc::string::String,
}
/// Configuration for the container service.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContainerConfig {
    /// Enables the container service
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// / Flag to make the container service required
    #[prost(bool, optional, tag = "2")]
    pub required: ::core::option::Option<bool>,
    /// / Maximum number of retries for the initialization of the service
    #[prost(uint32, optional, tag = "3")]
    pub max_retries: ::core::option::Option<u32>,
}
/// Configuration for the OTA service.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaConfig {
    /// Enables the container service
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// / Flag to make the container service required
    #[prost(enumeration = "ota_config::Reboot", optional, tag = "2")]
    pub reboot: ::core::option::Option<i32>,
    /// / Stream the OTA file directly.
    #[prost(bool, optional, tag = "3")]
    pub streaming: ::core::option::Option<bool>,
    /// / Rauc configuration
    #[prost(message, optional, tag = "4")]
    pub rauc: ::core::option::Option<ota_config::RaucConfig>,
}
/// Nested message and enum types in `OtaConfig`.
pub mod ota_config {
    /// Configuration for RAUC
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RaucConfig {
        /// Socket to communicate with RAUC
        #[prost(enumeration = "RaucDbus", tag = "1")]
        pub dbus_socket: i32,
    }
    /// Reboot behaviour after a OTA
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reboot {
        /// Default configuration
        Unspecified = 0,
        /// Default configuration
        Default = 1,
        /// The reboot is performed externally
        External = 2,
    }
    impl Reboot {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "REBOOT_UNSPECIFIED",
                Self::Default => "REBOOT_DEFAULT",
                Self::External => "REBOOT_EXTERNAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "REBOOT_UNSPECIFIED" => Some(Self::Unspecified),
                "REBOOT_DEFAULT" => Some(Self::Default),
                "REBOOT_EXTERNAL" => Some(Self::External),
                _ => None,
            }
        }
    }
    /// DBUS socket to communicate with the RAUC service
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum RaucDbus {
        /// Use the default configuration
        Unspecified = 0,
        /// Use the system bus
        System = 1,
        /// Use the session bus
        Session = 2,
    }
    impl RaucDbus {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "RAUC_DBUS_UNSPECIFIED",
                Self::System => "RAUC_DBUS_SYSTEM",
                Self::Session => "RAUC_DBUS_SESSION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RAUC_DBUS_UNSPECIFIED" => Some(Self::Unspecified),
                "RAUC_DBUS_SYSTEM" => Some(Self::System),
                "RAUC_DBUS_SESSION" => Some(Self::Session),
                _ => None,
            }
        }
    }
}
/// Configuration for the FileTransfer service.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileTransferConfig {
    /// Enables the service
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// Custom file storage directory.
    #[prost(string, optional, tag = "2")]
    pub storage_dir: ::core::option::Option<::prost::alloc::string::String>,
    /// Percentage of free space reserved for the system.
    ///
    /// For example 20 will reserve a minimum of 20% free space on a volume.
    #[prost(uint32, optional, tag = "3")]
    pub storage_reserved: ::core::option::Option<u32>,
}
/// Configuration for the Forwarder service.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForwarderConfig {
    /// Enables the service
    #[prost(bool, tag = "1")]
    pub enabled: bool,
}
/// / Configures a telemetry interface.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TelemetryConfig {
    /// Enables the telemetry interface.
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// Period in seconds to send the telemetry.
    #[prost(uint64, optional, tag = "2")]
    pub period_secs: ::core::option::Option<u64>,
}
/// Generated client implementations.
pub mod config_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Service for managing the configuration on the device runtime.
    #[derive(Debug, Clone)]
    pub struct ConfigServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ConfigServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ConfigServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ConfigServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ConfigServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Upload a new or replace a configuration file
        pub async fn put(
            &mut self,
            request: impl tonic::IntoRequest<super::PutRequest>,
        ) -> std::result::Result<tonic::Response<super::PutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/edgehog.deviceruntime.config.v1.ConfigService/Put",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "edgehog.deviceruntime.config.v1.ConfigService",
                        "Put",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod config_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ConfigServiceServer.
    #[async_trait]
    pub trait ConfigService: std::marker::Send + std::marker::Sync + 'static {
        /// Upload a new or replace a configuration file
        async fn put(
            &self,
            request: tonic::Request<super::PutRequest>,
        ) -> std::result::Result<tonic::Response<super::PutResponse>, tonic::Status>;
    }
    /// Service for managing the configuration on the device runtime.
    #[derive(Debug)]
    pub struct ConfigServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ConfigServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ConfigServiceServer<T>
    where
        T: ConfigService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/edgehog.deviceruntime.config.v1.ConfigService/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: ConfigService>(pub Arc<T>);
                    impl<T: ConfigService> tonic::server::UnaryService<super::PutRequest>
                    for PutSvc<T> {
                        type Response = super::PutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigService>::put(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ConfigServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "edgehog.deviceruntime.config.v1.ConfigService";
    impl<T> tonic::server::NamedService for ConfigServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
